### ISSUE TITLE
Release quizx with prebuilt wheels

### ISSUE THREAD

**Issue by rafaelha** [zxcalc/quizx#77]
I'd love if this package could be released very soon, with prebuilt wheels so that users don't need to have Rust installed.

@ABorgna - I saw that you are preparing for a [release here](https://github.com/zxcalc/quizx/pull/72). If there's anything I can do to help get this out quickly, I'd be happy to assist! (;

**Comment by ABorgna** [comment]
Version `0.1.0` is now in Pypi :)
https://pypi.org/project/quizx/
